language: node_js
node_js: node
cache: yarn
addons:
  chrome: stable
branches:
  except:
  - /^untagged/
install:
- npm install --global --upgrade yarn
- yarn install
- wget https://releases.hashicorp.com/terraform/0.12.0/terraform_0.12.0_linux_amd64.zip
- unzip terraform_0.12.0_linux_amd64.zip
- rm terraform_0.12.0_linux_amd64.zip
- export TF_VAR_S3_ID=$AWS_ACCESS_KEY_ID 
- export TF_VAR_S3_REGION=$AWS_DEFAULT_REGION 
- export TF_VAR_S3_SECRET=$AWS_SECRET_ACCESS_KEY
jobs:
  include:
  - stage: Extension Test
    if: ( type = push ) AND ( branch != master )
    script:
    - yarn gulp build
    - yarn mocha
    - ./terraform init -backend-config="bucket=limbo.chivuku.la" -backend-config="key=master.tfstate"
    - ./terraform plan
  - stage: Extension Deploy
    if: type = push
    script:
    - yarn gulp build
    - zip limbo.zip build/*
    deploy:
      provider: releases
      name: $TRAVIS_BUILD_NUMBER
      api_key: $GITHUB_TOKEN
      file: limbo.zip
      skip_cleanup: true
      on:
        all_branches: true
  - stage: Docassemble Deploy
    if: ( type = api ) AND ( branch = master )
    script:
    - yarn envsub config.yml config.yml
    - ./terraform init -backend-config="bucket=limbo.chivuku.la" -backend-config="key=master.tfstate"
    - ./terraform apply -auto-approve
