language: node_js
node_js: node
cache: yarn
addons:
  chrome: stable
install:
- npm install --global --upgrade yarn
- yarn install
- wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
- unzip terraform_0.11.10_linux_amd64.zip
- rm terraform_0.11.10_linux_amd64.zip
- yarn picaresque
jobs:
  include:
  - stage: Extension Test
    if: ( type = push ) AND ( branch != master )
    script:
    - yarn outdated
    - yarn mocha
    - yarn gulp build
  - stage: Extension Deploy
    if: ( type = push ) AND ( branch = master )
    script:
    - yarn gulp build
    - zip limbo.zip build/*
    deploy:
      provider: releases
      name: $TRAVIS_BUILD_NUMBER
      user: $GITHUB_USER
      api_key: $GITHUB_TOKEN
      file: limbo.zip
      skip_cleanup: true
  - stage: Docassemble Test
    if: ( type = api ) AND ( branch != master )
    script:
    - ./terraform init -backend-config="bucket=${TF_VAR_DOMAIN}" -backend-config="key=master.tfstate"
    - ./terraform plan
  - stage: Docassemble Deploy
    if: ( type = api ) AND ( branch = master )
    script:
    - ./terraform init -backend-config="bucket=${TF_VAR_DOMAIN}" -backend-config="key=master.tfstate"
    - ./terraform apply -auto-approve
