exitpage: https://docassemble.org
secretkey: ${SECRET_KEY}
default title: docassemble
default short title: doc
mail:
  mailgun api key: ${MAILGUN_API_KEY}
  mailgun domain: limbo.chivuku.la
  default sender: '"No Reply" <no-reply@limbo.chivuku.la>'
default interview: docassemble.law:data/questions/icop.yml
allow demo: True
ec2: true
