exitpage: https://docassemble.org
secretkey: ${SECRET_KEY}
default title: docassemble
default short title: doc
mail:
  mailgun api key: ${MAILGUN_API_KEY}
  mailgun domain: limbo.chivuku.la
  default sender: '"No Reply" <no-reply@limbo.chivuku.la>'
default interview: docassemble.law:data/questions/icop.yml
s3:
  enable: true
  access key id: AKIAIXSSFFYQIMGAET4Q
  secret access key: ${SECRET_ACCESS_KEY}
  bucket: limbo.chivuku.la
  region: us-east-1
ec2: true
