exitpage: https://docassemble.org
secretkey: ${SECRET_KEY}
default title: limbo
default short title: limbo
db:
  prefix: postgresql+psycopg2://
  name: docassemble
  user: docassemble
  password: abc123
  host: localhost
  port: Null
  table prefix: Null
mail:
  mailgun api key: ${MAILGUN_API_KEY}
  mailgun domain: limbo.chivuku.la
  default sender: '"No Reply" <no-reply@limbo.chivuku.la>'
default interview: docassemble.law:data/questions/icop.yml
allow demo: True
s3:
  enable: true
  access key id: ${AWS_ACCESS_KEY_ID}
  secret access key: ${AWS_SECRET_ACCESS_KEY}
  bucket: limbo.chivuku.la
  region: ${AWS_DEFAULT_REGION}
