on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
    - name: Build
      run: |
        npm install --upgrade yarn
        yarn install
        yarn gulp build
        zip limbo.zip -j build/*
    - uses: actions/upload-artifact@master
      with:
        name: extension
        path: limbo.zip
